import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/N6gSCJOJmym4isuCNlDxO5/BMS---VisualForce-Generator?node-id=2-12",
  {
    props: {
      // Map text content from actual layer names (without quotes)
      helloText: figma.textContent('Hello my John!'),
      bodyText: figma.textContent('We have a variety of updates for your list:'),
      
      // Map the updates-apex-repeat container
      updatesList: figma.children('updates-apex-repeat'),
      
      // Map the intro section
      introSection: figma.children('Intro'),
    },
    example: ({ helloText, bodyText, updatesList, introSection }) => html`<apex:page standardController="Account">
  <apex:pageBlock title="Updates Dashboard">
    
    <apex:pageBlockSection title="Welcome" columns="1">
      ${introSection}
      
      <apex:outputText value="${helloText}" 
                       style="font-size: 48px; font-weight: bold; display: block; margin-bottom: 20px;"/>
      
      <apex:outputText value="${bodyText}" 
                       style="font-size: 18px; margin-bottom: 15px; display: block;"/>
    </apex:pageBlockSection>
    
    <apex:pageBlockSection title="Updates List" columns="1">
      <apex:repeat var="update" value="{!updatesList}">
        <apex:outputText value="{!update.description}" escape="true" 
                         style="margin-bottom: 5px; display: block;"/>
      </apex:repeat>
    </apex:pageBlockSection>
    
  </apex:pageBlock>
</apex:page>`,
  },
)
